#!/bin/bash
function getCurrentRealPath(){
    source="${BASH_SOURCE[0]}"
    while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
      dir="$( cd -P "$( dirname "$source" )" && pwd )"
      source="$(readlink "$source")"
      [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    echo $dir
}

path=`getCurrentRealPath`
. $path/common.sh $path


code=`python $codeScript`
realpass="$rawpass $code"

if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
	ipAccount="$1 $powerop"
else
	ipAccount=`python $dictScript $@`
fi

echo "logging on $ipAccount"
$path/expect_jump.sh  $jump $user "$realpass"  $ipAccount
